"""Generate GB18030 lookup data from Python's standard codec; no game files are read."""
from pathlib import Path
pairs=[]
for first in range(0x81,0xff):
    for second in list(range(0x40,0x7f))+list(range(0x80,0xff)):
        pairs.append(ord(bytes([first,second]).decode('gb18030')))
ranges=[]
for point in range(126*10*126*10):
    x=point
    d=x%10+0x30;x//=10;c=x%126+0x81;x//=126;b=x%10+0x30;x//=10;a=x+0x81
    try: scalar=ord(bytes([a,b,c,d]).decode('gb18030'))
    except UnicodeDecodeError:continue
    if ranges and ranges[-1][1]+1==point and ranges[-1][2]+point-ranges[-1][0]==scalar:ranges[-1][1]=point
    else:ranges.append([point,point,scalar])
out=['// Generated by tools/make-gb18030.py from the standard GB18030 codec.','#pragma once','#include <cstdint>','namespace tenshi {','inline constexpr uint16_t gbPairs[]={']
for i in range(0,len(pairs),16):out.append(','.join(hex(x) for x in pairs[i:i+16])+',')
out+=['};','struct GbRange { uint32_t first,last,unicode; };','inline constexpr GbRange gbRanges[]={']
out += ['{%d,%d,%d},'%tuple(r) for r in ranges]
out+=['};','}']
Path(__file__).resolve().parents[1].joinpath('src/gb18030_table.hpp').write_text('\n'.join(out)+'\n')
print(len(pairs),'two-byte entries;',len(ranges),'four-byte ranges')
